---
- name: 'Create folder for AppImage files'
  ansible.builtin.file:
    path: <path>/Apps
    state: directory
    owner: '{{ config.user.name }}'
    group: '{{ config.user.name }}'
    mode: 0640

- name: Install AppImage for {{ appimage.name }}
  ansibl.builtin.include_tasks:
    file: 'install.yml'
  loop: '{{ config.appimages | flatten(levels=1) }}'
  loop_control:
    loop_var: appimage
  when: config.appimages
