---
- name: Install Flatpak for {{ flatpak.name }}
  ansible.builtin.include_tasks:
    file: 'install.yml'
  loop: '{{ config.flatpaks | flatten(levels=1) }}'
  loop_control:
    loop_var: flatpak
  when: config.flatpaks

- name: Install {{ flatpak.name }}
  community.general.flatpak:
    name: '{{ flatpak.name }}'
    method: user
    state: latest
  loop: '{{ config.flatpaks | flatten(levels=1) }}'
  loop_control:
    loop_var: flatpak
  when: config.flatpaks
